id = "zenc"
name = "Zen C"
version = "0.1"
schema_version = 1
description = "Zen C language support with LSP and syntax highlighting"
authors = ["PigeonCoding <wassimdzd@gmail.com>"]
repository = "https://github.com/PigeonCoding/zenc-zed"

[grammars.zenc]
repository = "https://github.com/PigeonCoding/tree-sitter-zenc"
commit = "892b837dc783c222ed2c59894338b25e0e991629"

[language_servers.zenc]
name = "Zen C LSP"
languages = ["Zen C"]
