id = "zenc"
name = "Zen C"
version = "0.0.1"
schema_version = 1
description = "Zen C language support with LSP and syntax highlighting"
authors = ["PigeonCoding <wassimdzd@gmail.com>"]
repository = "https://github.com/PigeonCoding/zenc-zed"

[grammars.zenc]
repository = "https://github.com/PigeonCoding/tree-sitter-zenc"
commit = "e7c5cdb5c138cb4989714e0e306bead94be4b445"

[language_servers.zenc]
name = "Zen C LSP"
languages = ["Zen C"]
